routes/web.php
Route::get('checknurseassign','WebsiteController@checknurseassign')->name('checknurseassign');
Route::get('re_schedule/{id}','WebsiteController@re_schedule')->name('re_schedule');
Route::post('re_schedule/{id}','WebsiteController@re_schedule_update')->name('re_schedule');
Route::get('/blog', 'WebsiteController@blog')->name('blog');

Route::get('/post/{slug}', 'WebsiteController@post')->name('post');
Route::get('/event', 'WebsiteController@event')->name('event');
Route::get('/news/{slug}', 'WebsiteController@news')->name('news');
Route::get('/about', 'WebsiteController@about')->name('about');

Route::get('/contact', 'WebsiteController@contact')->name('contact');
Route::post('/contact', 'WebsiteController@createEnquiry')->name('create-enquiry');
Route::post('/waitlist', 'WebsiteController@storeWaitlist')->name('store-waitlist');

Route::get('/cart', 'WebsiteController@cart')->name('cart');
Route::get('/checkout', 'WebsiteController@checkout')->name('checkout');

Route::get('/dump', 'WebsiteController@dump')->name('dump');
Route::get('/web-home', 'WebsiteController@home')->name('web-home');
Route::get('/informed-consent', 'WebsiteController@informedConsent')->name('informed-consent');
Route::get('/my-account', 'WebsiteController@myAcccount')->name('my-account');
Route::get('/privacy', 'WebsiteController@privacy')->name('privacy');
Route::get('/terms', 'WebsiteController@terms')->name('terms');

Route::get('nurse/register', 'WebsiteController@nurseRegisteration')->name('nurse-register');

//track order
Route::get('trackorder','HomeController@trackorder')->name('trackorder');

Route::group(['prefix'=>'nurse', 'middleware' => 'role:nurse'], function(){
    Route::get('home', 'NurseController@index')->name('nurse');
    Route::get('orders', 'NurseController@getorders')->name('orders');
    Route::Post('orders/{id}', 'NurseController@order_status')->name('orders.{id}');
    Route::get('profile', 'NurseController@profile')->name('profile');
});
// auth routes
Auth::routes();

// post login routes
Route::get('/home', 'HomeController@index')->name('home');
//testing mail
Route::get('/sendmail', 'WebsiteController@sendmail')->name('sendmail');

//user profile
Route::get('profile','HomeController@myprofile')->name('profile');
//profile upload
Route::post('profile-picture', 'HomeController@updatePicture')->name('update-picture');
// admin routes
Route::group(['prefix'=>'admin', 'middleware' => 'role:super-admin'], function(){

    // admin dashboard
    Route::get('/dashboard', 'AdminController@dashboard')->name('admin-dashboard');
    Route::get('/profile', 'AdminController@profile')->name('admin-profile');
    Route::post('/update-profile', 'AdminController@update')->name('admin-update-profile');
    Route::post('/update-profile-picture', 'AdminController@updatePicture')->name('admin-update-picture');

    // content management
    Route::get('/content', 'ContentController@index')->name('admin-content');
    Route::get('/add-content', 'ContentController@add')->name('admin-add-content');
    Route::post('/create-content', 'ContentController@create')->name('admin-create-content');
    Route::get('/delete-content/{id}', 'ContentController@delete')->name('admin-delete-content');
    Route::get('/edit-content/{id}', 'ContentController@edit')->name('admin-edit-content');
    Route::post('/update-content', 'ContentController@update')->name('admin-update-content');
    Route::get('/delete-media/{id}', 'ContentController@deletMedia')->name('admin-delete-media');

    // test management
    Route::resource('test','TestController');
    Route::get('delete-test-media/{id}','TestController@deletMedia');
    Route::get('delete-test/{id}', 'TestController@delete')->name('admin-delete-test');

    // membership management
    Route::resource('membership','MembershipController');
    Route::get('delete-membership-media/{id}','MembershipController@deletMedia');
    Route::get('delete-membership/{id}', 'MembershipController@delete')->name('admin-delete-membership');
    Route::get('membership_status/{id}', 'MembershipController@status')->name('membership_status');
    
    //configuration
    Route::get('configuration','ConfigController@index')->name('configuration');
    Route::post('emailconfiguration','ConfigController@emailconfiguration')->name('emailconfiguration');
    Route::post('paymentgateway','ConfigController@paymentgateway')->name('paymentgateway');
    Route::post('googleapi','ConfigController@googleapi')->name('googleapi');
    Route::post('config_setting','ConfigController@config_setting')->name('config_setting');
    //Addons
    Route::resource('addon','AddonController');
    Route::get('delete-addon-media/{id}','AddonController@deletMedia');
    Route::get('delete-addon/{id}', 'AddonController@delete')->name('admin-delete-addon');

    //product purchase order
    Route::get('order','OrderController@index')->name('order');
    Route::get('order/show/{id}','OrderController@show')->name('order-show');
    Route::post('order/assign/{id}','OrderController@assign')->name('order-assign');
    
    // posts management
    Route::get('/posts', 'PostController@index')->name('admin-posts');
    Route::get('/add-post', 'PostController@add')->name('admin-add-post');
    Route::post('/create-post', 'PostController@create')->name('admin-create-post');
    Route::get('/edit-post/{id}', 'PostController@edit')->name('admin-edit-post');
    Route::post('/update-post', 'PostController@update')->name('admin-update-post');
    Route::get('/delete-post/{id}', 'PostController@delete')->name('admin-delete-post');
    Route::get('/delete-post-media/{id}', 'PostController@deletMedia')->name('admin-delete-post-media');

    // locations management
    Route::get('/locations', 'LocationController@index')->name('admin-locations');
    Route::get('/add-location', 'LocationController@add')->name('admin-add-location');
    Route::post('/create-location', 'LocationController@create')->name('admin-create-location');
    Route::get('/edit-location/{id}', 'LocationController@edit')->name('admin-edit-location');
    Route::post('/update-location', 'LocationController@update')->name('admin-update-location');
    Route::get('/delete-location/{id}', 'LocationController@delete')->name('admin-delete-location');
    Route::get('/delete-location-media/{id}', 'LocationController@deletMedia')->name('admin-delete-location-media');

    // news & events management
    Route::get('/events', 'EventController@index')->name('admin-events');
    Route::get('/add-event', 'EventController@add')->name('admin-add-event');
    Route::post('/create-event', 'EventController@create')->name('admin-create-event');
    Route::get('/edit-event/{id}', 'EventController@edit')->name('admin-edit-event');
    Route::post('/update-event', 'EventController@update')->name('admin-update-event');
    Route::get('/delete-event/{id}', 'EventController@delete')->name('admin-delete-event');
    Route::get('/delete-event-media/{id}', 'EventController@deletMedia')->name('admin-delete-event-media');

    // faqs management
    Route::get('/faq', 'FAQController@index')->name('admin-faq');
    Route::get('/add-faq', 'FAQController@add')->name('admin-add-faq');
    Route::post('/create-faq', 'FAQController@create')->name('admin-create-faq');
    Route::get('/edit-faq/{id}', 'FAQController@edit')->name('admin-edit-faq');
    Route::post('/update-faq', 'FAQController@update')->name('admin-update-faq');
    Route::get('/delete-faq/{id}', 'FAQController@delete')->name('admin-delete-faq');

    // enquiry management
    Route::get('/enquiries', 'EnquiryController@index')->name('admin-enquiries');
    Route::get('/delete-enquiry/{id}', 'EnquiryController@delete')->name('admin-delete-enquiry');
    Route::get('/change-status-enquiry/{id}/{status}', 'EnquiryController@changeStatus')->name('admin-change-status-enquiry');

    // waiting list
    Route::resource('waiting', 'WaitingController')->only(['index', 'destroy']);

    // product management
    Route::resource('products', 'ProductController');
    Route::post('products/change-status/{id}', 'ProductController@changeStatus')->name('status');
    Route::resource('products', 'ProductController');
    Route::post('products/delete-product-media/{id}', 'ProductController@deletMedia');

    // category management
    Route::resource('categories', 'CategoryController');
    Route::post('delete-categories-media/{id}/{i}', 'CategoryController@deletMedia');

    //customer management
    Route::get('user', 'UserManagementConroller@getCustomer')->name('customer');
    Route::get('/user/edit/{id}', 'UserManagementConroller@editCustomer')->name('customer.edit');
    Route::patch('/user/update', 'UserManagementConroller@updateCustomer')->name('customer.update');
    Route::get('manager', 'UserManagementConroller@getManager')->name('manager');
    Route::get('/manager/edit/{id}', 'UserManagementConroller@editManager')->name('manager.edit');
    Route::patch('/manager/update', 'UserManagementConroller@updateManager')->name('manager.update');
    Route::get('nurse', 'UserManagementConroller@getNurse')->name('nurse');
    Route::get('/nurse/edit/{id}', 'UserManagementConroller@editNurse')->name('nurse.edit');
    Route::patch('/nurse/update', 'UserManagementConroller@updateNurse')->name('nurse.update');
    Route::post('change-user-status/{id}', 'UserManagementConroller@changeStatus')->name('active');
    Route::post('change-user-document-status/{id}', 'UserManagementConroller@changeDocumentStatus')->name('doc');
    Route::get('add-manager', 'UserManagementConroller@createManager')->name('createManager');
    Route::post('create-manager', 'UserManagementConroller@storeManager')->name('storeManager');

    // admin under development
    Route::get('/under-development', function(){
        $meta = [
            'title' => 'Under Development',
            'breadcrumbs' => [
                'Home' => route('admin-dashboard')
            ]
        ];

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['parent_id', 'name', 'description', 'image'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $meta = [
            'title' => 'Categories',
            'breadcrumbs' => [
                'Home' => route('admin-dashboard'),
                'Categories' => route('categories.index')
            ]
        ];

        $categories = Category::orderBy('id','desc')->paginate(env('PAGINATION_RECORDS'));
        return view('admin.categories.index', compact('meta','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        $meta = [
            'title' => 'Add Category',
            'breadcrumbs' => [
                'Home' => route('admin-dashboard'),
                'Add Category' => route('categories.create')
            ]
        ];
        $categories = Category::all();
        return view('admin.categories.create', compact('meta', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = Category::create([
            'name' => $request->name,
            'parent_id' => isset($request->parent_id) ? $request->parent_id : 0,
            'description' => $request->description
        ]);

        $images = [];
        if($request->media){
            foreach($request->media as $image){
                $file = $this->saveBase64Image('uploads/categories/', $image);                
                    array_push($images, $file);
            }
        }
        $category->image = json_encode($images);
        $category->save();

        Session::flash('success', 'Category Created.'); 
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $meta = [
            'title' => 'Edit Category',
            'breadcrumbs' => [
                'Home' => route('admin-dashboard'),
                'Edit Category' => route('categories.edit',$id)
            ]
        ];

        $categories = Category::find($id);
        $cate = Category::all();
        return view('admin.categories.edit', compact('meta','categories', 'cate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::find($request->id);

        $category->name = $request->name;
        $category->parent_id = (isset($request->parent_id) ? $request->parent_id : 0);
        $category->description = $request->description;

        $images = json_decode($category->image);
        if($request->media){
            foreach($request->media as $image){
                $file = $this->saveBase64Image('uploads/categories/', $image);                
                    array_push($images, $file);
            }
        }
        $category->image = json_encode($images);
        $category->save();

        Session::flash('success', 'Category Updated.'); 
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $c = Category::find($id);
        if(!empty($c->image)){
        foreach(json_decode($c->image) as $m){
            try{
                unlink($m);
            } catch(\Exception $e) {
                // nothing to do
            }
        }
    }
        $c->delete();

        return response()->json([
            "status"=>true
        ]);
    }


    /**
     * This function is used to delete category Media.
     *
     * @param [int] $id
     * @param [int] $i
     * @return void
     */
    public function deletMedia($id, $i)
    {
        $m = Category::find($id);

        try{
            $x = json_decode($m->image);
            if(!empty($x))
            {
                unlink($x[$i]);
                unset($x[$i]);
            }
            $m->image = json_encode($x);
            $m->save();
        } catch(\Exception $e) {
            // nothing to do
        }

        return response()->json([
            "status"=>true
        ]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layout.admin-layout')

@section('content')

@include('admin.partials.breadcrumbs')

<section class="content">
    <div class="container-fluid">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">&nbsp;</h3>
                <div class="card-tools">
                    <a href="{{ route('categories.index') }}" class="btn btn-danger">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <form action="{{ route('categories.store') }}" method="post" id="create-form" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Name</label>
                                        <input type="text" class="form-control" name="name" placeholder="Name">
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label>Please Select Category</label>
                                        <select class="form-control" name="parent_id">
                                            <option value="">Please Select Category</option>
                                            @if($categories->isNotEmpty())
                                                @foreach($categories as $val)
                                                <option value="{{$val->id}}">{{$val->name}}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Description</label>
                                        <textarea class="form-control description" id="description" name="description" required></textarea>
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Category Media</label>
                                        <input type="file" class="form-control image">
                                    </div>
                                </div>
                                <div class="row col-sm-12" id="media-preview">
                                    
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group text-right">
                                        <br/>
                                        <button type="submit" class="btn btn-success">Add Category</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section('pagescript')

<!--Image Crop Wizard-->
<div class="modal fade" id="crop-tool" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalLabel">Adjust Your Image</h5>
            </div>
            <div class="modal-body">
                <div class="img-container">
                    <div class="row">
                        <div class="col-md-12 text-center" style="padding-left:0px;">
                            <img id="image" src="">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="crop">Okay, Save</button>
            </div>
        </div>
    </div>
</div>
<!--Image Crop Wizard-->

<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js" integrity="sha512-37T7leoNS06R80c8Ulq7cdCDU5MNQBwlYoy1TX/WUsLFC2eYNqtKlV0QjH7r8JpG/S0GUMZwebnVFLPd6SU5yg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/additional-methods.min.js" integrity="sha512-XZEy8UQ9rngkxQVugAdOuBRDmJ5N4vCuNXCh8KlniZgDKTvf7zl75QBtaVG1lEhMFe2a2DuA22nZYY+qsI2/xA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.css"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.js"></script>

<script>
    // Wait for the DOM to be ready
    $(function() {

        $(".description").summernote();

        $("#create-form").validate({
            rules: {
                name: {
                    required: true
                },
                description: {
                    required: true
                }
            },
            messages: {
                name: {
                    required: "Name cannot be left blank"
                },
                description: {
                    required: "Description cannot be left blank"
                }
            },
            submitHandler: function(form) {
                form.submit();
            }
        });
    });
</script>

<script>
    var $modal = $('#crop-tool');
    var image = document.getElementById('image');
    var cropper;
    var selectedImage = 0;

    $("body").on("change", ".image", function (e) {
        var files = e.target.files;
        var done = function (url) {
            image.src = url;
            $modal.modal('show');
        };
        var reader;
        var file;
        var url;
        if (files && files.length > 0) {
            file = files[0];
            if (URL) {
                done(URL.createObjectURL(file));
            } else if (FileReader) {
                reader = new FileReader();
                reader.onload = function (e) {
                    done(reader.result);
                };
                reader.readAsDataURL(file);
            }
        }
    });

    $modal.on('shown.bs.modal', function () {
        cropper = new Cropper(image, {
            //aspectRatio: 1,
            preview: '.preview'
        });
    }).on('hidden.bs.modal', function () {
        cropper.destroy();
        cropper = null;
    });

    $("#crop").click(function () {
        canvas = cropper.getCroppedCanvas({
            // width: 160,
            // height: 160,
        });
        canvas.toBlob(function (blob) {
            url = URL.createObjectURL(blob);
            var reader = new FileReader();
            reader.readAsDataURL(blob);
            reader.onloadend = function () {
                var base64data = reader.result;
                selectedImage++;
                let html = `
                    <div class="col-sm-3" id="selected-image-${selectedImage}" class="text-center">
                        <input type="text" name="media[]" value="${base64data}" style="display:none;">
                        <img src="${base64data}" class="image-preview">
                        <a href="javascript:void(0)" onclick="removeImage(${selectedImage})" class="image-preview-remove">
                            <i class="fa fa-trash text-danger image-remove-btn"></i>
                        </a>
                    </div>
                `;

                $("#media-preview").append(html);
                $modal.modal('hide');
                
            }
        });
    });

    function removeImage(id){
        $("#selected-image-"+id).remove();
        selectedImage--;
    }
</script>
@stop

@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout.admin-layout')

@section('content')

@include('admin.partials.breadcrumbs')

<section class="content">
    <div class="container-fluid">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">&nbsp;</h3>
                <div class="card-tools">
                    <a href="{{ route('categories.create') }}" class="btn btn-primary">
                        <i class="fas fa-plus"></i> Add New
                    </a>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title text-danger">Edit only if you are sure that what it is going to change.</h3>
                                <div class="card-tools">
                                    <?php echo $categories->render(); ?>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0" style="height: 300px;">
                                <table class="table table-bordered table-head-fixed text-nowrap">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Name</th>
                                            <th>Parent</th>
                                            <th>Description</th>
                                            <th>Image</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach($categories as $cat)
                                        <tr id="record-{{ $cat->id }}">
                                            <td>#{{ $loop->index+1 }}</td>
                                            <td>{{ $cat->name }}</td>
                                            <td>{{ $cat->parent_id == 0 ? 'Parent' : getCategoryName($cat->parent_id) }}</td>
                                            <td>{!! $cat->description !!}</td>
                                            @php
                                            $image = json_decode($cat->image)
                                            @endphp
                                            <td>
                                                @if(!empty($image))
                                                @foreach($image as $val)
                                                <img src="{{ asset($val) }}" width="100px"/>
                                                @endforeach
                                                @endif
                                            </td>
                                            <td class="text-center">
                                                <a href="{{ route('categories.edit', $cat->id) }}" class="btn btn-info"><i class="fa fa-edit"></i></a>
                                                <button onclick="deletecat(<?php echo $cat->id ?>)" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section('pagescript')
@if(\Session::has('success'))
<script>
    swal("Success!", "{{ Session::get('success') }}", "success");
</script>
@endif

<script>
    function deletecat(id) {
        swal({
            title: "Are you sure?",
            text: "You want to delete this record?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        }).then((flag) => {
            if (flag) {
                fetch("{{ url('admin/categories') }}/"+id, {
                    method: "DELETE",
                    headers: {
                        "Content-type": "application/json; charset=UTF-8",
                        'X-CSRF-TOKEN': '{{csrf_token()}}'
                    }
                }).then(response => response.json()).then( res => {
                    if(res.status){
                        document.getElementById('record-'+id).remove();
                        swal("Record deleted!", {
                            icon: "success",
                        });
                    }
                });
            }
        });
    }
</script>
@stop

@endsection