routes/web.php
<?php

use Illuminate\Support\Facades\Route;

// website routes
Route::get('/', 'WebsiteController@landingPage')->name('landing');

//production
Route::get('/production/{slug}', 'WebsiteController@production')->name('production');
//member
Route::get('/becomeamenber', 'WebsiteController@becomeamenber')->name('becomeamenber');
//frontend faq
Route::get('/faq', 'WebsiteController@faq')->name('faq');
//checkout
Route::get('checkout', 'WebsiteController@checkout')->name('checkout');
Route::post('checkout', 'WebsiteController@checkoutStore')->name('checkout');
//payment
Route::get('stripe/{id}', 'WebsiteController@stripe');
Route::post('stripe/{id}', 'WebsiteController@stripePost')->name('stripe.post');
//order list
Route::get('orders','WebsiteController@orders')->name('orders');
Route::post('orders/{id}','WebsiteController@complete_orders')->name('complete_orders');
//tracking
Route::get('order/tracking/{id}','WebsiteController@tracking')->name('order-tracking');
//order details
Route::get('order/details/{id}','WebsiteController@details')->name('order-details');
//check nurse assign schedule
Route::get('checknurseassign','WebsiteController@checknurseassign')->name('checknurseassign');
Route::get('re_schedule/{id}','WebsiteController@re_schedule')->name('re_schedule');
Route::post('re_schedule/{id}','WebsiteController@re_schedule_update')->name('re_schedule');
Route::get('/blog', 'WebsiteController@blog')->name('blog');

Route::get('/post/{slug}', 'WebsiteController@post')->name('post');
Route::get('/event', 'WebsiteController@event')->name('event');
Route::get('/news/{slug}', 'WebsiteController@news')->name('news');
Route::get('/about', 'WebsiteController@about')->name('about');

Route::get('/contact', 'WebsiteController@contact')->name('contact');
Route::post('/contact', 'WebsiteController@createEnquiry')->name('create-enquiry');
Route::post('/waitlist', 'WebsiteController@storeWaitlist')->name('store-waitlist');

Route::get('/cart', 'WebsiteController@cart')->name('cart');
Route::get('/checkout', 'WebsiteController@checkout')->name('checkout');

Route::get('/dump', 'WebsiteController@dump')->name('dump');
Route::get('/web-home', 'WebsiteController@home')->name('web-home');
Route::get('/informed-consent', 'WebsiteController@informedConsent')->name('informed-consent');
Route::get('/my-account', 'WebsiteController@myAcccount')->name('my-account');
Route::get('/privacy', 'WebsiteController@privacy')->name('privacy');
Route::get('/terms', 'WebsiteController@terms')->name('terms');

Route::get('nurse/register', 'WebsiteController@nurseRegisteration')->name('nurse-register');

//track order
Route::get('trackorder','HomeController@trackorder')->name('trackorder');

Route::group(['prefix'=>'nurse', 'middleware' => 'role:nurse'], function(){
    Route::get('home', 'NurseController@index')->name('nurse');
    Route::get('orders', 'NurseController@getorders')->name('orders');
    Route::Post('orders/{id}', 'NurseController@order_status')->name('orders.{id}');
    Route::get('profile', 'NurseController@profile')->name('profile');
});
// auth routes
Auth::routes();

// post login routes
Route::get('/home', 'HomeController@index')->name('home');
//testing mail
Route::get('/sendmail', 'WebsiteController@sendmail')->name('sendmail');

//user profile
Route::get('profile','HomeController@myprofile')->name('profile');
//profile upload
Route::post('profile-picture', 'HomeController@updatePicture')->name('update-picture');
// admin routes
Route::group(['prefix'=>'admin', 'middleware' => 'role:super-admin'], function(){

    // admin dashboard
    Route::get('/dashboard', 'AdminController@dashboard')->name('admin-dashboard');
    Route::get('/profile', 'AdminController@profile')->name('admin-profile');
    Route::post('/update-profile', 'AdminController@update')->name('admin-update-profile');
    Route::post('/update-profile-picture', 'AdminController@updatePicture')->name('admin-update-picture');

    // content management
    Route::get('/content', 'ContentController@index')->name('admin-content');
    Route::get('/add-content', 'ContentController@add')->name('admin-add-content');
    Route::post('/create-content', 'ContentController@create')->name('admin-create-content');
    Route::get('/delete-content/{id}', 'ContentController@delete')->name('admin-delete-content');
    Route::get('/edit-content/{id}', 'ContentController@edit')->name('admin-edit-content');
    Route::post('/update-content', 'ContentController@update')->name('admin-update-content');
    Route::get('/delete-media/{id}', 'ContentController@deletMedia')->name('admin-delete-media');

    // test management
    Route::resource('test','TestController');
    Route::get('delete-test-media/{id}','TestController@deletMedia');
    Route::get('delete-test/{id}', 'TestController@delete')->name('admin-delete-test');

    // membership management
    Route::resource('membership','MembershipController');
    Route::get('delete-membership-media/{id}','MembershipController@deletMedia');
    Route::get('delete-membership/{id}', 'MembershipController@delete')->name('admin-delete-membership');
    Route::get('membership_status/{id}', 'MembershipController@status')->name('membership_status');
    
    //configuration
    Route::get('configuration','ConfigController@index')->name('configuration');
    Route::post('emailconfiguration','ConfigController@emailconfiguration')->name('emailconfiguration');
    Route::post('paymentgateway','ConfigController@paymentgateway')->name('paymentgateway');
    Route::post('googleapi','ConfigController@googleapi')->name('googleapi');
    Route::post('config_setting','ConfigController@config_setting')->name('config_setting');
    //Addons
    Route::resource('addon','AddonController');
    Route::get('delete-addon-media/{id}','AddonController@deletMedia');
    Route::get('delete-addon/{id}', 'AddonController@delete')->name('admin-delete-addon');

    //product purchase order
    Route::get('order','OrderController@index')->name('order');
    Route::get('order/show/{id}','OrderController@show')->name('order-show');
    Route::post('order/assign/{id}','OrderController@assign')->name('order-assign');
    
    // posts management
    Route::get('/posts', 'PostController@index')->name('admin-posts');
    Route::get('/add-post', 'PostController@add')->name('admin-add-post');
    Route::post('/create-post', 'PostController@create')->name('admin-create-post');
    Route::get('/edit-post/{id}', 'PostController@edit')->name('admin-edit-post');
    Route::post('/update-post', 'PostController@update')->name('admin-update-post');
    Route::get('/delete-post/{id}', 'PostController@delete')->name('admin-delete-post');
    Route::get('/delete-post-media/{id}', 'PostController@deletMedia')->name('admin-delete-post-media');

    // locations management
    Route::get('/locations', 'LocationController@index')->name('admin-locations');
    Route::get('/add-location', 'LocationController@add')->name('admin-add-location');
    Route::post('/create-location', 'LocationController@create')->name('admin-create-location');
    Route::get('/edit-location/{id}', 'LocationController@edit')->name('admin-edit-location');
    Route::post('/update-location', 'LocationController@update')->name('admin-update-location');
    Route::get('/delete-location/{id}', 'LocationController@delete')->name('admin-delete-location');
    Route::get('/delete-location-media/{id}', 'LocationController@deletMedia')->name('admin-delete-location-media');

    // news & events management
    Route::get('/events', 'EventController@index')->name('admin-events');
    Route::get('/add-event', 'EventController@add')->name('admin-add-event');
    Route::post('/create-event', 'EventController@create')->name('admin-create-event');
    Route::get('/edit-event/{id}', 'EventController@edit')->name('admin-edit-event');
    Route::post('/update-event', 'EventController@update')->name('admin-update-event');
    Route::get('/delete-event/{id}', 'EventController@delete')->name('admin-delete-event');
    Route::get('/delete-event-media/{id}', 'EventController@deletMedia')->name('admin-delete-event-media');

    // faqs management
    Route::get('/faq', 'FAQController@index')->name('admin-faq');
    Route::get('/add-faq', 'FAQController@add')->name('admin-add-faq');
    Route::post('/create-faq', 'FAQController@create')->name('admin-create-faq');
    Route::get('/edit-faq/{id}', 'FAQController@edit')->name('admin-edit-faq');
    Route::post('/update-faq', 'FAQController@update')->name('admin-update-faq');
    Route::get('/delete-faq/{id}', 'FAQController@delete')->name('admin-delete-faq');

    // enquiry management
    Route::get('/enquiries', 'EnquiryController@index')->name('admin-enquiries');
    Route::get('/delete-enquiry/{id}', 'EnquiryController@delete')->name('admin-delete-enquiry');
    Route::get('/change-status-enquiry/{id}/{status}', 'EnquiryController@changeStatus')->name('admin-change-status-enquiry');

    // waiting list
    Route::resource('waiting', 'WaitingController')->only(['index', 'destroy']);

    // product management
    Route::resource('products', 'ProductController');
    Route::post('products/change-status/{id}', 'ProductController@changeStatus')->name('status');
    Route::resource('products', 'ProductController');
    Route::post('products/delete-product-media/{id}', 'ProductController@deletMedia');

    // category management
    Route::resource('categories', 'CategoryController');
    Route::post('delete-categories-media/{id}/{i}', 'CategoryController@deletMedia');

    //customer management
    Route::get('user', 'UserManagementConroller@getCustomer')->name('customer');
    Route::get('/user/edit/{id}', 'UserManagementConroller@editCustomer')->name('customer.edit');
    Route::patch('/user/update', 'UserManagementConroller@updateCustomer')->name('customer.update');
    Route::get('manager', 'UserManagementConroller@getManager')->name('manager');

resources/views/admin/partials/breadcrumbs.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">{{ $meta['title'] }}</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    @foreach($meta['breadcrumbs'] as $key => $value)
                        <li class="breadcrumb-item {{ $value == '' ? 'active' : '' }}"><a href="{{ $value }}">{{ $key }}</a></li>
                    @endforeach
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/admin/partials/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2019-2021 <a href="https://healthiv.com">HealthIV</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.1.0
    </div>
</footer>

resources/views/admin/partials/head.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HealthIV Admin | {{ $meta['title'] }}</title>

    <!--favicons-->
    <link rel="icon" href="{{ url('assets/images/cropped-favicon-32x32.jpg') }}" sizes="32x32"/>
    <link rel="icon" href="{{ url('assets/images/cropped-favicon-192x192.jpg') }}" sizes="192x192"/>
    <link rel="apple-touch-icon" href="{{ url('assets/images/cropped-favicon-180x180.jpg') }}"/>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('/')}}admin/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="{{asset('/')}}admin/plugins/summernote/summernote-bs4.min.css">
    <!--cripper js-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.6/cropper.css"/>

    <link rel="stylesheet" href="{{asset('/')}}admin/dist/css/style.css">
</head>

resources/views/admin/partials/loader.blade.php
<!-- Preloader -->
<div class="preloader flex-column justify-content-center align-items-center" style="background:#f5f4e9 !important;">
    <img class="animation__shake" src="{{asset('/')}}admin/dist/img/loader-01.gif" alt="HealthIV">
</div>

resources/views/admin/partials/nav.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index.html" class="nav-link">{{ $meta['title'] }}</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        
        <!-- Profile Management -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-user-circle"></i> &nbsp; {{ \Auth::user()->name }}
            </a>
            <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-divider"></div>
                <a href="{{ route('admin-profile') }}" class="dropdown-item">
                    <i class="fas fa-id-card mr-2"></i> Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                    <i class="fas fa-unlock mr-2"></i> Logout
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </div>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

resources/views/admin/partials/scripts.blade.php
<!-- jQuery -->
<script src="{{asset('/')}}admin/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('/')}}admin/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{asset('/')}}admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- ChartJS -->
<script src="{{asset('/')}}admin/plugins/chart.js/Chart.min.js"></script>
<!-- Sparkline -->
<script src="{{asset('/')}}admin/plugins/sparklines/sparkline.js"></script>
<!-- JQVMap -->
<script src="{{asset('/')}}admin/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="{{asset('/')}}admin/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
<!-- jQuery Knob Chart -->
<script src="{{asset('/')}}admin/plugins/jquery-knob/jquery.knob.min.js"></script>
<!-- daterangepicker -->
<script src="{{asset('/')}}admin/plugins/moment/moment.min.js"></script>
<script src="{{asset('/')}}admin/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{asset('/')}}admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<script src="{{asset('/')}}admin/plugins/summernote/summernote-bs4.min.js"></script>
<!-- overlayScrollbars -->
<script src="{{asset('/')}}admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
<!-- AdminLTE App -->
<script src="{{asset('/')}}admin/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('/')}}admin/dist/js/demo.js"></script>
<!--sweetalert-->
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

@yield('pagescript')

resources/views/admin/partials/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ route('admin-dashboard') }}" class="brand-link text-center">
        <span class="brand-text font-weight-light"> Health </span><span class="text-icon-blue">IV</span>
    </a>
    <!--sidebar opens-->
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Administration</li>
                <li class="nav-item">
                    <a href="{{ route('order') }}" class="nav-link">
                        <i class="nav-icon fa fa-hashtag text-icon-blue"></i>
                        <p>Orders</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-shopping-cart text-icon-blue"></i>
                        <p>
                            Product Management
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('categories.index') }}" class="nav-link">
                                <i class="fa fa-barcode nav-icon"></i>
                                <p>Categories</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('products.index') }}" class="nav-link">
                                <i class="fa fa-shopping-basket nav-icon"></i>
                                <p>Products</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('addon.index') }}" class="nav-link">
                                <i class="fa fa-cart-plus nav-icon"></i>
                                <p>Addons</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-users text-icon-blue"></i>
                        <p>
                            User Management
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('customer') }}" class="nav-link">
                                <i class="fa fa-user nav-icon"></i>
                                <p>Customers</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('manager') }}" class="nav-link">
                                <i class="fa fa-user-secret nav-icon"></i>
                                <p>Managers</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('nurse') }}" class="nav-link">
                                <i class="fa fa-user-plus nav-icon"></i>
                                <p>Nurses</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-folder text-icon-blue"></i>
                        <p>
                            Reports
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-th nav-icon"></i>
                                <p>Sales</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-th nav-icon"></i>
                                <p>Payouts</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-th nav-icon"></i>
                                <p>DSR</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{ route('test.index') }}" class="nav-link">
                        <i class="nav-icon fa fa-file text-icon-green" ></i>
                        <p>Tests</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('membership.index') }}" class="nav-link">
                        <i class="nav-icon fa fa-file text-icon-green" ></i>
                        <p>Membership</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-posts') }}" class="nav-link">
                        <i class="nav-icon fa fa-file text-icon-green" ></i>
                        <p>Blog Posts</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-locations') }}" class="nav-link">
                        <i class="nav-icon fa fa-map-marker text-icon-green"></i>
                        <p>Locations</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-events') }}" class="nav-link">
                        <i class="nav-icon fa fa-camera text-icon-green"></i>
                        <p>Events / News</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-faq') }}" class="nav-link">
                        <i class="nav-icon fa fa-question text-icon-green"></i>
                        <p>FAQ</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-content') }}" class="nav-link">
                        <i class="nav-icon fas fa-columns text-icon-yellow"></i>
                        <p>Content</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('admin-enquiries') }}" class="nav-link">
                        <i class="nav-icon fa fa-exclamation-triangle text-icon-yellow"></i>
                        <p>Enquiries</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('waiting.index') }}" class="nav-link">
                        <i class="nav-icon fa fa-spinner text-icon-yellow"></i>
                        <p>Waiting List</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fa fa-cog text-icon-yellow"></i>
                        <p>
                            Settings
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-calendar nav-icon"></i>
                                <p>Working Days</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-clock nav-icon"></i>
                                <p>Available Time</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('admin-under-development') }}" class="nav-link">
                                <i class="fa fa-bed nav-icon"></i>
                                <p>Holidays</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ route('configuration') }}" class="nav-link">
                                <i class="fa fa-envelope nav-icon"></i>
                                <p>Configuration</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
    <!--sidebar ends-->
</aside>